# Official boilerplate
title: TourHunter Help Center
email: insert@email.tld # wx: set actual
description: '' # wx: set actual

twitter_username: jekyllrb # wx set actual
github_username:  jekyll # wx set actual
repository: 4u70m493/help-tourhunter-com # wx: set actual

# URLs and links
baseurl: ''
url: 'https://help.tourhunter.com'

# Permalinks
permalink: /:category/:title

# Collections
collections:
  category:
    output: true #  This allows us to generate pages for each category where we can list all posts under that category.
    permalink: /category/:name # /getting-started.html

# i18n settings
#languages: ["en", "ru"]
#exclude_from_localizations: ["javascript", "images", "css", "docs"]
# Note: commented out, because jekyll-multiple-languages-plugin was removed, bcs it's unsupported by GH Pages ATM

# Build settings
theme: jekyll-theme-cayman
markdown: kramdown

plugins:
- jekyll-feed
- jekyll-github-metadata

# _pages subdir is convenient for storing all pages
include: ['_pages']

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
 - .sass-cache/
 - .jekyll-cache/
 - gemfiles/
 - Gemfile
 - Gemfile.lock
 - node_modules/
 - vendor/bundle/
 - vendor/cache/
 - vendor/gems/
 - vendor/ruby/
 - .idea/
 - CNAME
 - README.md
